version: '3'

networks:
  bridge_network:
    name: dest_${APP_PORT}
services:
  mariadb:
    container_name: dest_${APP_PORT}_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: dest-toolkit
    image: mariadb:latest
    networks:
      - bridge_network
    restart: always
    volumes:
      - ./${APP_PORT}/mariadb:/var/lib/mysql
  