version: '3'

networks:
  bridge_network:
    name: dest_${APP_PORT}
services:
  mariadb:
    container_name: dest_${APP_PORT}_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: dest_${APP_PORT}_mariadb
    image: mariadb:latest
    networks:
      - bridge_network
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./${APP_PORT}/mariadb:/var/lib/mysql
  mssql:
    container_name: dest_${APP_PORT}_mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: dest_${APP_PORT}_mssql
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      - bridge_network
    ports:
      - 1433:1433
    restart: always
    volumes:
      - ./${APP_PORT}/mssql:/var/opt/mssql
