version: '3'

networks:
  dest_network:
    name: dest_network_${DEST_PORT}
services:
  mariadb:
    container_name: dest-mariadb-${DEST_PORT}
    environment:
      MARIADB_ROOT_PASSWORD: dest-toolkit
    image: mariadb:latest
    networks:
      - dest_network
    restart: always
    volumes:
      - ./${DEST_PORT}/mariadb:/var/lib/mysql
  